openapi: 3.0.0
info:
  title: PricePal API
  version: 1.0.0
  description: >
    Questa è la documentazione delle API dell'applicazione PricePal.
    Le API sono divise in due parti. 
    La prima è quella relativa alla gestione dell'account di un utente. 
    La seconda è quella relativa alla creazione, modifica ed eliminazione delle liste.
    Nella seconda parte sono anche presenti le api utilizzate per gestire le liste di oggetti mai inseriti da ciascun utente, 
    utili per semplificare l'inserimento di oggetti usati spesso nelle liste.
    Troverai qui una descrizione dettagliata di ciascun endpoint, dei parametri richiesti e delle varie risposte possibili.

tags:
  - name: account
    description: Operazioni sugli account
  - name: liste
    description: Operazioni sulle liste
  - name: oggetti
    description: Operazioni sugli oggetti mai inseriti dall'utente
paths:
  /account/login:
    post:
      summary: Autenticazione
      tags: [account]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  description: Indirizzo email dell'account
                  example: example.name@gmail.com
                password:
                  type: string
                  description: Password dell'account
                  example: password
      responses:
        '200':
          description: Successo
          content:
            application/json:
              example:
                message: 'Login effettuato con successo'
                account:
                  $ref: '#/components/schemas/Account'
        '400':
          description: Dati mancanti o non validi
          content:
            application/json:
              example:
                error: 'Dati mancanti o non validi'
        '401':
          description: Password errata
          content:
            application/json:
              example:
                error: 'Password errata'
        '404':
          description: Account non trovato
          content:
            application/json:
              example:
                error: 'Nessun account associato alla mail: email@example.com'
        '500':
          description: Errore durante il login
          content:
            application/json:
              example:
                error: 'Errore durante il login'

  /account/registra:
    post:
      summary: Registrazione di un nuovo account
      tags: [account]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
      responses:
        '200':
          description: Successo
          content:
            application/json:
              example:
                message: 'Account registrato con successo'
                account:
                  $ref: '#/components/schemas/Account'
        '400':
          description: Dati mancanti o non validi
          content:
            application/json:
              example:
                error: 'Dati mancanti o non validi'
        '409':
          description: Account già registrato
          content:
            application/json:
              example:
                error: 'Esiste già un account registrato con questa email'
        '500':
          description: Errore durante la registrazione
          content:
            application/json:
              example:
                error: 'Errore durante la registrazione'

  /account/elimina/{idAccount}:
    delete:
      summary: Eliminazione dell'account
      tags: [account]
      parameters:
        - name: idAccount
          in: path
          required: true
          description: Id account dell'account da eliminare
          schema:
            type: string
      responses:
        '200':
          description: Successo
          content:
            application/json:
              example:
                message: 'Account eliminato con successo'
        '400':
          description: Dati mancanti o non validi
          content:
            application/json:
              example:
                error: 'Dati mancanti o non validi'
        '404':
          description: Account non trovato
          content:
            application/json:
              example:
                error: 'Account non trovato'
        '500':
          description: Errore durante l'eliminazione dell'account
          content:
            application/json:
              example:
                error: 'Errore durante l eliminazione dell account'

  /account/modifica/{idAccount}:
      put:
        summary: Modifica dell'account
        tags: [account]
        parameters:
          - name: idAccount
            in: path
            required: true
            description: ID dell'account da modificare
            schema:
              type: string
              example: 656d99094e20e227874eac45
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                    format: email
                    description: Nuovo indirizzo email dell'account
                    example: example.name@gmail.com
                  nome:
                    type: string
                    description: Nuovo nome dell'account
                    example: ExampleName
                  nuovaPassword:
                    type: string
                    description: Nuova password dell'account
                    example: password
                  vecchiaPassword:
                    type: string
                    description: Vecchia password dell'account
                    example: password
        responses:
          '200':
            description: Successo
            content:
              application/json:
                example:
                  message: 'Account modificato con successo'
                  account:
                    $ref: '#/components/schemas/Account'
          '400':
            description: Id account errato
            content:
              application/json:
                example:
                  error: 'Id account non definito o non valido'
          '401':
            description: Vecchia password errata
            content:
              application/json:
                example:
                  error: 'Vecchia password non corretta'
          '404':
            description: Account non trovato
            content:
              application/json:
                example:
                  error: 'Account non trovato'
          '500':
            description: Errore durante la modifica dell'account
            content:
              application/json:
                example:
                  error: 'Errore durante la modifica dell account'

  /liste:
    post:
      summary: Aggiungi una nuova lista
      tags: [liste]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                titolo:
                  type: string
                  description: Titolo della lista
                oggetti:
                  type: array
                  items:
                    type: string
                  description: Oggetti della lista
                idAccount:
                  type: string
                  description: ID dell'account associato alla lista
      responses:
        '200':
          description: Successo
          content:
            application/json:
              example:
                message: 'Lista aggiunta con successo'
                lista_aggiunta:
                  $ref: '#/components/schemas/Lista'
        '400':
          description: Dati mancanti o non validi
          content:
            application/json:
              example:
                error: 'Dati mancanti o non validi'
        '500':
          description: Errore durante l'aggiunta della lista
          content:
            application/json:
              example:
                error: 'Errore durante l aggiunta della lista'
  
  /liste/{idAccount}:
    get:
      summary: Ottieni tutte le liste di un account
      tags: [liste]
      parameters:
        - name: idAccount
          in: path
          required: true
          description: ID dell'account
          schema:
            type: string
            example: 656d99094e20e227874eac45
      responses:
        '200':
          description: Successo
          content:
            application/json:
              example:
                message: 'Liste dell account ottenute con successo'
                liste:
                  type: array
                  items:
                    $ref: '#/components/schemas/Lista'
        '400':
          description: Dati mancanti o non validi
          content:
            application/json:
              example:
                error: 'Dati mancanti o non validi'
        '404':
          description: Liste non trovate
          content:
            application/json:
              example:
                error: 'Liste non trovate'
        '500':
          description: Errore durante il recupero delle liste
          content:
            application/json:
              example:
                error: 'Errore durante il recupero delle liste dell account'

  /liste/{idLista}:
    delete:
      summary: Elimina una lista
      tags: [liste]
      parameters:
        - name: idLista
          in: path
          required: true
          description: ID della lista da eliminare
          schema:
            type: string
      responses:
        '200':
          description: Successo
          content:
            application/json:
              example:
                message: 'Lista eliminata con successo'
        '400':
          description: Dati mancanti o non validi
          content:
            application/json:
              example:
                error: 'Dati mancanti o non validi'
        '404':
          description: Lista non trovata
          content:
            application/json:
              example:
                error: 'Lista non trovata'
        '500':
          description: Errore durante l'eliminazione della lista
          content:
            application/json:
              example:
                error: 'Errore durante l eliminazione della lista'

    put:
      summary: Modifica una lista
      tags: [liste]
      parameters:
        - name: idLista
          in: path
          required: true
          description: ID della lista da modificare
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                titolo:
                  type: string
                  description: Nuovo titolo della lista
                oggetti:
                  type: array
                  items:
                    type: string
                  description: Nuovi oggetti della lista
      responses:
        '200':
          description: Successo
          content:
            application/json:
              example:
                message: 'Lista modificata con successo'
                lista_modificata:
                  $ref: '#/components/schemas/Lista'
        '400':
          description: Dati mancanti o non validi
          content:
            application/json:
              example:
                error: 'Dati mancanti o non validi'
        '404':
          description: Lista non trovata
          content:
            application/json:
              example:
                error: 'Lista non trovata'
        '500':
          description: Errore durante la modifica della lista
          content:
            application/json:
              example:
                error: 'Errore durante la modifica della lista'

  /oggetti/{idAccount}:
    get:
      summary: Ottieni tutti gli oggetti inseriti da un account
      tags: [oggetti]
      parameters:
        - name: idAccount
          in: path
          required: true
          description: ID dell'account
          schema:
            type: string
            example: 656d99094e20e227874eac45
      responses:
        '200':
          description: Successo
          content:
            application/json:
              example:
                message: 'Oggetti mai inseriti dall account ottenuti con successo'
                oggetti:
                  type: array
                  items:
                    $ref: '#/components/schemas/OggettiListe'
        '400':
          description: Dati mancanti o non validi
          content:
            application/json:
              example:
                error: 'Dati mancanti o non validi'
        '500':
          description: Errore durante il recupero degli oggetti
          content:
            application/json:
              example:
                error: 'Errore durante il recupero degli oggetti'

    put:
      summary: Aggiungi un nuovo oggetto alla lista dell'account
      tags: [oggetti]
      parameters:
        - name: idAccount
          in: path
          required: true
          description: ID dell'account
          schema:
            type: string
            example: 656d99094e20e227874eac45
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                oggetto:
                  type: string
                  description: Nuovo oggetto da aggiungere alla lista
      responses:
        '200':
          description: Successo
          content:
            application/json:
              example:
                message: 'Oggetto aggiunto con successo'
                lista_modificata:
                  $ref: '#/components/schemas/OggettiListe'
        '400':
          description: Dati mancanti o non validi
          content:
            application/json:
              example:
                error: 'Dati mancanti o non validi'
        '500':
          description: Errore durante l'aggiunta dell'oggetto alla lista
          content:
            application/json:
              example:
                error: 'Errore durante l aggiunta dell oggetto alla lista'

    delete:
      summary: Rimuovi la lista di oggetti mai inseriti da un account
      tags: [oggetti]
      parameters:
        - name: idAccount
          in: path
          required: true
          description: ID dell'account
          schema:
            type: string
      responses:
        '200':
          description: Successo
          content:
            application/json:
              example:
                message: 'Lista di oggetti rimossa con successo'
        '400':
          description: Dati mancanti o non validi
          content:
            application/json:
              example:
                error: 'Dati mancanti o non validi'
        '404':
          description: Lista di oggetti non trovata
          content:
            application/json:
              example:
                error: 'Lista di oggetti non trovata'
        '500':
          description: Errore durante la rimozione della lista di oggetti
          content:
            application/json:
              example:
                error: 'Errore durante la rimozione della lista di oggetti'
  
  /oggetti/rimuovi/{idAccount}:
    put:
      summary: Rimuovi un oggetto da una lista dell'account
      tags: [oggetti]
      parameters:
        - name: idAccount
          in: path
          required: true
          description: ID dell'account
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                oggetto:
                  type: string
                  description: Nome dell'oggetto da rimuovere
      responses:
        '200':
          description: Successo
          content:
            application/json:
              example:
                message: 'Elemento eliminato con successo'
                lista_modificata:
                  $ref: '#/components/schemas/OggettiListe'
        '400':
          description: Dati mancanti o non validi
          content:
            application/json:
              example:
                error: 'ID account non valido'
        '404':
          description: Nessun documento trovato con l'ID account specificato
          content:
            application/json:
              example:
                error: 'Nessun documento trovato con l ID account specificato'
        '500':
          description: Errore durante la rimozione dell'oggetto
          content:
            application/json:
              example:
                error: 'Errore durante la rimozione dell oggetto'

                 
components:
  schemas:
    Account:
      type: object
      properties:
        nome:
          type: string
          description: Nome dell'account
          example: ExampleName
        email:
          type: string
          format: email
          description: Indirizzo email dell'account
          example: example.name@gmail.com
        password:
          type: string
          description: Password dell'account
          example: password

    Lista:
      type: object
      properties:
        titolo:
          type: string
          description: Titolo della lista
          example: titolo
        oggetti:
          type: array
          items:
            type: string
          description: Oggetti della lista
          example:
            - Primo oggetto
            - Secondo oggetto
            - Terzo oggetto
        idAccount:
          type: string
          description: ID dell'account associato alla lista
          example: idAccountValido
        dataUltimaModifica:
          type: string
          format: date-time
          description: Data dell'ultima modifica della lista
          example: "2023-12-01T15:30:00Z"

    OggettiListe:
      type: object
      properties:
        oggetti:
          type: array
          items:
            type: string
          description: Lista di oggetti
          example: ["Oggetto1", "Oggetto2", "Oggetto3"]
        idAccount:
          type: string
          description: ID dell'account associato alla lista di oggetti
          example: idAccountValido